import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import QueryProvider from "./Provider/QueryProvider";
import Sidebar from "./Components/Sidebar";
import TopBar from "./Components/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased max-w-[1320px] mx-auto`}
      >
        <QueryProvider>
          <div>
            <Sidebar />
            <TopBar />
            <div className="pl-0 lg:pl-[280px] pt-17">
              <div className="border-r min-h-[calc(100vh-70px)] relative border-[#E9E9E9]">
                {children}
              </div>
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
